---
title: "Домашнее задание 1"
output:
  pdf_document: default
header-includes:
- \usepackage[russian]{babel}
- \usepackage{hyperref}
- \hypersetup{ colorlinks = true, urlcolor = blue}
---

*Файл с выполненным заданием необходимо загрузить на Dropbox до дедлайна, указанного на сайте.* 

*Домашние задания, сданные после срока, оцениваются с использованием понижающих коэффициентов: опоздание в пределах часа – штраф 10% от полученной оценки, в пределах суток – штраф 20%, в пределах недели – штраф 50%. Домашние задания, сданные через неделю после указанного срока и позже, не принимаются и не оцениваются.*

*Если при проверке работ установлен факт нарушения академической этики, студент получает оценку «0» за данную работу. Работа студента, предоставившего свою работу для списывания, также аннулируется.*

1.  Создать файл `hw1-surname.Rmd`, где surname — Ваша фамилия латиницей.

2.  Воспроизвести файл, опубликованный по [ссылке](http://rpubs.com/AllaT/rprog-hw1): набрать в созданном файле `hw1-surname.Rmd` текст с соответствующей разметкой, добавить необходимый код (см.ниже) и график.

3.  Сохранить изменения в Rmd-файле, «связать» html-файл. Скомпилированный html-файл должен выглядеть так же, как и файл, предложенный для репликации.

Код для графика:

```{r, eval=FALSE}
freqs <- c(10, 4, 1) # частоты
lvls <- c("Начальный", "Средний", "Продвинутый") # уровни
colors <- c("royalblue", "yellow", "red") # цвета для диаграммы
percs <- round(freqs / sum(freqs) * 100, 2) # относительные частоты (в процентах)
labels <- paste(lvls, percs) # склеить уровни и проценты - для подписей к диаграмме
labels_fin <- paste(labels,"%", sep = "") # добавить знак % к подписям
pie(freqs, labels = labels_fin, col = colors, main = "Уровень владения R") 
```
